site_name: Data Science Project Management with CRISP-DM

repo_name: "Preetish2603/End-to-End-Bank-Subscription-Classifier"
repo_url: "https://github.com/Preetish2603/End-to-End-Bank-Subscription-Classifier"
